### ISSUE TITLE
Discord Support

### ISSUE THREAD

**Issue by VenomStyx** [Visualistic-Studios/Media-Manager#13]
## Overview

Support for schedule posting to Discord

Essentially just a Discord Bot that posts in a specific channel or channels. Can use the same bot for all or different bots for each, up to the user when they add the account. 

- [x] Text Webhooks 
- [x] Media 
- [x] Mentions

**Comment by VenomStyx** [comment]
Alright so I switched my path from trying to implement a full discord bot to simple webhooks. They're easier to manage and they provide all the features that this needs. No reason to sit around waiting for a bot to spin up when you can send a quick post request. 

Currently text posts are **done**, however posts with attachments still need work. The request throws no errors but also doesn't return anything. 

🤷‍♂️

**Comment by VenomStyx** [comment]
It's pretty much working for Discord at the moment, though I'm not considering it truly functional until it can mention users & roles. Post formatting might be necessary as well.

**Comment by VenomStyx** [comment]
Discord webhooks have an 8mb upload limit.

**Comment by VenomStyx** [comment]
Initial Discord Support complete! 

Will need to add post formatting system (#37)  in order to do much better. Also need to address post object serialization (#26) so that posts can be extended properly.

**Comment by Shingii** [comment]
how can i run this project on personal server?
